AlgoLeadMe/AlgoLeadMe-8

- dhlee777/bfs/숨바꼭질.cpp
https://www.acmicpc.net/problem/1697
2시간40분
수빈이의 각위치에서 **+1,-1,*2 의 탐색**을 진행 할 수 있고 최소시간을 구해야 하기때문에 bfs를 이용해야  한다고 생각했습니다. _(토마토익기 문제를 그전에풀어봤는데  그문제 와 비슷한유형의 문제인데 토마토는 동서남북으로 탐색을 진행 할 수 있고 시작지점 도 2개였었습니다)_ 
<br><br><br>
입력으로는 수빈이의 위치, 동생의 위치가 각각 주어지기때문에  변수 `start`,`end`에 각각 위치값을 받아준뒤 그 변수들을 이용하여 bfs를 진행해줍니다.
<br><br><br>
`dt`배열은 수빈이의 위치에 따른 최소 시간을 나타내 주는 배열입니다.
`dt[7]=3`이라면 수빈이가 시작 위치에서 7까지 가는데 3초가 걸렸다는 뜻입니다.
`dt`배열은 처음 선언 시 전부 0으로 초기화 되기 때문에 값이 0일시 방문 되지 않은 점으로 생각했습니다.
그러나 처음 시작 위치의 경우 값이 (`dt[start]=0`)(방문 되지 않은 점) 이기에 나중에 이상한 시간 값이 들어갈 수 있는데 이것은 결과 값에 영향을 미치지 못합니다.
bfs함수의 경우  일단 수빈이의 시작 지점 을 큐에 넣어줍니다. 그 후 이제 큐가 빌 때까지 계속 while문을 진행해줍니다.
<br><br><br><br><br><br>
while문의 경우 일단 큐에서 제일 앞에 있는 위치를 꺼낸 다음 ,
**1)만약 그 위치가 동생의 위치일 경우**
동생을 찾은 것이므로 더 이상의 탐색이 필요하지 않으므로 `dt[end]`를 반환하고 함수를 종료해줍니다. …
> 1-dhlee777

- yuyu0830/탐색/1865.cpp
https://www.acmicpc.net/problem/1865
1865 웜홀
3일...
풀이 : https://blog.naver.com/abdds1166/223380026932
알고리즘 : https://blog.naver.com/abdds1166/223380023141
벨만-포드 알고리즘을 사용했습니다 :)
:D
> 1-yuyu0830

- InSange/DP/7579.cpp
- InSange/README.md
[앱](https://www.acmicpc.net/problem/7579)
10시간
우리가 알고 있던 DP 배낭 문제랑 비슷했습니다.
1. ```메모리 바이트(M)```를 기준으로 나열한다.
2. 모든 ```앱(N)```들을 방문하면서 메모리마다 돌아본다.
3. M값을 충족하는 최소 비용을 반환한다.
해당 방법으로 ```메모리 바이트(M)```를 기준으로 접근하였을 때 
메모리(M)는 최소 1에서 10,000,000만큼 나열이되어야하고
앱(N)은 최소 1개에서 100까지 존재하기에 만약 모든 메모리 바이트를 앱들이 돈다고 가정하였을 경우
100 * 10,000,000 만큼 돌아야하며 시간 복잡도 및 메모리 초과 문제가 발생할 수 있다.
1. ```비용(c)```를 기준으로 나열한다.
2. 모든 ```비용(c)```를 더한 값을 최대 크기로 지정한다.
3. 비용을 기점으로 ```앱 메모리(m)```를 배열에 할당하여 현재 비용을 뺀 값에 ```앱 메모리(m)```을 더한 값과 현재 메모리 비용을 비교한다.
4. 소모되는 '''비용(c)''' 값보다 할당해준 비용이 작을 경우를 대비하여 최대 비용에서 0으로 접근하게 끔 한다.
```비용(c)```를 기준으로 나열했을 경우 ```앱(N)``` 개수 만큼 비교가 더해진다 했을 때 100*100 만큼의 메모리 비용이 필요하다.
참고 블로그 :https://wisdom-990629.tistory.com/entry/C-%EB%B0%B1%EC%A4%80-7579%EB%B2%88-%EC%95%B1
> 2024-03-15 앱

- dhlee777/README.md
- dhlee777/dp/쉬운계단수.cpp
https://www.acmicpc.net/problem/10844
2시간
이 문제는 자릿수가 주어지고 그전 자릿수의 계단수를 저장해두었다 계속 재활용해주어야하기때문에 `dp`알고리즘을 써야한다 생각했습니다.  
`stair_num[i][j]` 배열은 `i`는자릿수`j`는0~9 인 숫자로 `i번째자리에 숫자j`가 왔을때의 가능한 `계단수`입니다.
즉` stair_num[5][6]`의 경우 `5번째자리에 6이왔을때 가능한 계단수`의  값을 가집니다.   
이 경우  가능한 계단수는 (4번째자리에 5가온 계단수+4번째자리 7이 온 계단수)입니다.
```
long long int stair_num[101][11];   //n번째자리에 m이왔을때 가능한 계단의수
ios_base::sync_with_stdio(false);
cin.tie(NULL);
int num;
cin >> num;    //첫째자리수는 0은 제외하고 어떤수가 오든 경우의수는 1이다.
for (int j = 1; j <= 9; j++)
stair_num[1][j] = 1;
for (int i = 2; i <=num; i++) {     //어떤자리수가 0일경우 그전자리수는 1이어야한다.
for (int j =0; j <10; j++) {
if (!j) stair_num[i][j] = stair_num[i - 1][1];
stair_num[i][j] = (stair_num[i - 1][j - 1] + stair_num[i - 1][j + …
```
> 2-dhlee777

- seongwon030/README.md
- seongwon030/bfs/토마토3차원.py
[토마토](https://www.acmicpc.net/problem/7569)
3시간
```python
from collections import deque
m,n,h = map(int,input().split())
tomato = []
for i in range(h):
tomato.append([list(map(int,input().split())) for _ in range(n)])
queue = deque([]) # 좌표 -> 리스트
dx, dy, dz = [-1,1,0,0,0,0], [0,0,-1,1,0,0,], [0,0,0,0,-1,1] # 좌,우,하,상,아래,위 -> 좌표 이동
ans = 0 # 최소 날짜
cnt = 0
for i in range(h): # dz
for j in range(n): # dy
for k in range(m): # dx
if tomato[i][j][k] == 1: # 1인 경우 토마토가 있으므로 큐에 append
queue.append((i,j,k))
while queue:
z,y,x = queue.popleft() # 첫 번째 좌표
for i in range(6):
nx,ny,nz = dx[i] + x, dy[i] + y, dz[i] + z
if 0 <= nx < m and 0 <= ny < n  and 0 <= nz < h and tomato[nz][ny][nx] == 0:
tomato[nz][ny][nx] = tomato[z][y][x] + 1 # 그 다음 칸으로 이동
queue.append((nz,ny,nx)) 
cnt+=1
flag = False 
for i …
```
> 3-seongwon030

- dhlee777/README.md
- dhlee777/union-find/집합의표현.cpp
https://www.acmicpc.net/problem/1717
3시간
`유니온 파인드(uion-find)`란 대표적인  그래프 알고리즘으로 특정 두 노드가 같은집합에 속해있는지 판별해주는 알고리즘이다.
크게 특정 두 집합을 합치는  `union 연산`과 루트노드를 찾는 `find 연산`으로 이루어진다.
우선 `parent 배열`은 어떤노드의 `부모노드`를 저장하는 배열로 최종적으로는 어떤노드의 `루트노드`가 저장된다.
```cpp
#include<stdio.h>
int parent[1000001];          //어떤수의 부모노드를 저장하는 배열 ,최종적으로는 그 수의 루트노드가 저장된다.
int find_parent(int a) {        //어떤 노드의 루트노드를 찾는 함수
if (a == parent[a])  return a;
else  return parent[a]=find_parent(parent[a]);
}
void add (int a,int b) {     
a = find_parent(a);      //a의 루트 노드를 찾고
b = find_parent(b);		//b의 루트노드를 찾아
if (a == b) return;     //두 수의 루트노드가 같으면 이미 같은집합에 있으므로 함수 종료
if (a < b) parent[b] = a;   //더 작은 수가 루트가 된다.
else parent[a] = b;
}
void compare(int a, int b) {
a = find_parent(a);
b = …
```
> 3-dhlee777

- dhlee777/README.md
- dhlee777/bfs/바이러스.cpp
https://www.acmicpc.net/problem/2606
2시간
이문제는 단순한 `bfs`를 이용해 풀 수 있지만 `유니온파인드`를 이용해서도 한번 풀어보았다.
첫번재풀이는 그냥 단순히` bfs`를 이용하여 풀었다. `1번 컴퓨터`와 연결된 컴퓨터는 모조리 감염되는것이므로 bfs를 이용하여` 1번컴퓨터와 연결된 모든 컴퓨터를 다 탐색`해주며 `카운트` 하면 된다. 여기서 `주의해야할점`은 맨처음에 시작정점을 방문했다고 표시해주는것! `(visited[a]=1) ` 맨처음 이부분을 놓쳤어서 계속 이상한 답이 나왔다..
``` cpp
#include<vector>
#include<queue>
vector<int>com_edge[101];    //컴퓨터간의 간선의 정보를 저장하는 이차원벡터
int visited[101];   //감염된 컴퓨터인지 확인하기위한 배열
queue<int> q;
int coun = 0;
void bfs(int a) {     //bfs 를 위한 함수
q.push(a);
visited[a] = 1;
while (!q.empty()) {
int com = q.front();
q.pop();
for (int i = 0; i < com_edge[com].size(); i++) {
int com_linked = com_edge[com][i];
if (!visited[com_linked])
{
q.push(com_linked);
coun++;            //방문되지않은 연결된 컴퓨터일경우 카운트 …
```
> 4-dhlee777

- yuyu0830/README.md
- yuyu0830/분할정복/10830.cpp
[행렬 제곱](https://www.acmicpc.net/problem/10830)
30분
[블로그 풀이](https://blog.naver.com/abdds1166/223396328090)
정보보호론에서 암호를 구현할 때 사용하는 `Double-and-Add Method` 라는 방식을 사용했습니다.
숫자 `n`을 `b`번 제곱할 때, `n`을 `b`번 직접 다 곱하는 방법도 있습니다.
하지만  (n*n)^2 이렇게 지금 곱하고 있는 수 자체를 제곱해 연산을 줄일 수 있습니다.
따라서 기준이 되는 배열 `crit`, 현재 수를 저장하는 배열 `arr` 두개를 두어 n을 곱할 때는 `arr` * `crit`, 즉 `Adding`를 하고 , 자체를 곱할 때는 `arr` * `arr`, 즉 `Doubling`를 실행해 연산했습니다.
`Double-and-Add Method`는 2진수가 제일 앞에 bit를 제외한 뒤, 앞에서부터 1이면 `* 2 + 1`, 0이면 `* 2` 를 수행해 해당 수를 만들 수 있다는 점에 착안했습니다.
26을 계산한 예시
bit wise 연산을 통해 각 bit별 수를 확인해 Doubling와 Adding 연산 여부를 결정했습니다. 이후는 1000 나머지 연산만 해주면 끝!
bit shift는 한 번에 16 이상 못합니다! b 번 제곱해야하고, `b`가 최대 100,000,000,000 라서 `1 << 37` 로 쓰려고 했는데 자꾸 오류가 뜨네요....
> 4 yuyu0830

- seongwon030/README.md
- seongwon030/bfs/점프점프.py
[점프점프](https://www.acmicpc.net/problem/11060)
2시간
1. <code>현재 인덱스와 점프 횟수</code>를 큐에 넣는다.
2. <code>방문 여부 체크</code>를 위한 리스트를 만든다.
3. 큐에 요소가 있을 때 까지 
1) <code>현재 인덱스와 점프인덱스 튜플</code>을 큐에서 꺼낸다.
2) 만약 <code>현재 인덱스가 마지막 칸에 해당</code>하면 jump 출력 후 종료한다.
3) 아니면 <code>k 리스트 안의 숫자 이하</code>만큼 반복한다 
4) 다음 인덱스를 방문하지 않은 상태면 점프횟수에 1을 더하고 큐에 추가 후 방문처리
4. exit 안 하면 -1 출력
```python
from collections import deque
n = int(input())
k = list(map(int,input().split()))
cur, jump = 0,0
queue = deque()
queue.append((cur,jump))  # 현재 인덱스, 점프 인덱스
visited = [] 
while queue:
cur, jump = queue.popleft()
if cur == len(k)-1:   # 현재 인덱스가 마지막 칸에 해당하면 jump출력 후 종료
print(jump)
exit()
for i in range(1, k[cur]+1):  # k안에 있는 숫자 이하만큼 오른쪽으로 점프 가능
next = cur + i 
if next not in visited:
queue.append((next, jump+1)) …
```
> 5-seongwon030

- dhlee777/README.md
- dhlee777/mst/최소스패닝트리.cpp
https://www.acmicpc.net/problem/1197
2시간
`최소 스패닝(신장) 트리(mst)`란 주어진 그래프의 모든 정점을 연결하는 부분그래프중에서 그 `가중치의 합이 최소인 트리`를 의미합니다. 
이 조건을 만족하기 위해서는 
**1.간선의 개수가` (정점-1)`개 존재하여 한다.
2.사이클이 존재하지 않아야한다.(트리의 특성)**
이 두가지 조건에 신경을 써서 문제를 풀었습니다.
저는 이 최소 신장 트리를 구하기 위해 `그리디 방식`을 이용하는` kruskal 알고리즘`을 사용하였습니다.  이 알고리즘은 우선 
주어진 간선들 중 `우선순위 큐`를 이용하여 
**1.`최소 간선`부터 뽑아낸다. (greedy)
2.그 간선을 추가했을때 사이클이 발생하는지 `union-find`를 통해 확인해준다.
3.if (사이클이 발생할경우) 반복문으로 돌아가서 `큐에서 다시 간선을 뽑는다.`
else(사이클 발생x) 그 간선을 `카운트`(추가)해주고 간선의 가중치를 `sum` 에 더해준다.
4. 만약 `(간선의개수==정점-1)`이 된다면 정점들이 다 연결된것이므로 종료한다.
5. 가중치의 합이 저장된` sum`을 출력해준다.**
``` cpp
#include<queue>
int parent[10001];  //부모노드를 저장해주는 배열
int sum, cnt = 0;
int v_num, e_num;
priority_queue < pair<int, pair<int, int>>, vector<pair<int, pair<int, …
```
> 5-dhlee777

- yuyu0830/탐색/2239.cpp
[스도쿠](https://www.acmicpc.net/problem/2239)
1시간
비어있는 스도쿠를 채우는 문제입니다. 하지만 스도쿠의 칸이 많이 비어있어 여러가지 답이 나올 수 있는 문제입니다. 따라서 문제의 *답이 여러 개 있다면 그 중 사전식으로 앞서는 것을 출력한다. 즉, 81자리의 수가 제일 작은 경우를 출력한다.* 에 맞게끔 출력하면 됩니다.
어떤 식으로 풀까 고민하던 중 위의 *사전식으로 앞서는 것* 이라는 부분에서 아이디어를 얻었습니다. 앞에서부터 1~9까지 대입하며 백트래킹으로 탐색하면 되겠구나 싶었습니다.
제일 `첫번째 칸`부터 `81번째 칸` 까지 재귀함수를 통해 탐색(DFS) 합니다. 해당 칸이 숫자가 있다면 다음 칸을 탐색, 없다면 해당 칸을 탐색합니다.
solve 함수를 통해 해당 칸에 들어갈 수 있는 숫자를 체크하고, 탐색합니다. 스도쿠의 룰 상 같은 가로, 세로 줄에 같은 숫자가 있으면 안되고, 9x9 보드를 9개의 3x3으로 칸을 나눴을 때, 현재 탐색 중인 칸이 속한 3x3 칸에서도 같은 숫자가 있으면 안됩니다. 2중 for문을 통해 현재 탐색하는 칸에 `숫자 i` 가 겹치는게 없는지 `j` 를 통해 체크합니다. 만약 문제가 없다면 현재 칸에 `i`를 넣은 채로 다음 칸을 탐색합니다. 만약 겹친다면 `i` 는 넘어갑니다.
for문이 종료될 때까지 정답이 없었다면 현재의 스도쿠 상태로는 답이 나올 수 없는 상태이기 때문에 `false`를 리턴합니다. 만약 82번째 칸을 탐색, 즉 마지막 칸까지 채워졌다면 `true`를 리턴합니다. 각 재귀 함수에서 `true`가 리턴되면 …
> 5-yuyu0830

- dhlee777/README.md
- dhlee777/backtracking/스타트와링크.cpp
https://www.acmicpc.net/problem/14889
하루
하루 동안 계속 생각해봤지만 도저히 아이디어가 떠오르지 않아서 답을 봐버렸다..
일단 이 문제는 `총 n명의 선수(짝수)를 두팀(start와 link)로 나누는데` 각 선수끼리 같은팀이 됐을때 능력치가 있다. 예를들어 `stats[2][3]` 은2번선수와 3번선수가 같은팀이됐을때 `능력치`를 나타낸다. ` 변수 start`는 start팀의 `능력치 합`  `link`는 link 팀의 
`능력치 합`을 나타낸다. 결국 구하고자하는것은 `start와 link의 차가 최소가 되는 값 inf`이다.
``` cpp
for ( int i = num; i < total_num; i++) {  //전에 확인했던 선수는 확인하지 않기위해 현재선수부터 시작 
visited[i] = 1;            //현재선수에  방문표시,방문했다면 start팀이 된다.방문안했다면 link팀     
dfs(cnt + 1, i + 1);
visited[i] = 0;      //탐색이 끝난후 다시 방문되지않았다고 초기화해준다.
}
```
1.`현재선수num`부터 제일 `마지막선수`까지 탐색을해준다.
2.현재선수에 `방문 표시`를 해주고  `카운트를 1증가`시키고 `다음선수로dfs` 진행
3.다른경우의 수를 위해 탐색이 끝난후` visited[i]=0으로 초기화`
만약 `탐색한 선수의 수`가` 전체선수의 절반`이 된다면  밑의 코드를 실행한다.(반만 탐색해서` start팀`으로 할당해주면  나머지는 자동으로` link팀 `처리)
``` cpp
void …
```
> 6-dhlee777

- yuyu0830/README.md
- yuyu0830/수학/2437.cpp
[저울](https://www.acmicpc.net/problem/2437)
1시간
[블로그 풀이](https://blog.naver.com/abdds1166/223405298133)
---
>늦은 시간 다 같이 동방에서 각자 공부를 하던 중
>알고리즘 대장님이 갑작스럽게 문제 하나를 던졌다.
​
>그 소식에 5명이 달려들어 함께 풀기 시작했고
>집단 지성을 사용해 오만때만 해결책을 던지기 시작했다.
>
>시간 복잡도가 2^1000 이 나오기도 하고 1000! 가 나오기도 하고 세상 정신 없었는데
>
>한 분께서 빛나는 아이디어를 내면서 상황은 반전을 맞이하게 된다.
>이 자리를 빌어 나봉님께 감사 인사를 드립니다
>
>완전한 해결책은 아니였지만 새로운 아이디어를 기반으로 색다른 해결 방안을 모색하기 시작했고
>결국 다 함께 해결책을 찾아내었다.
>
>늦은 밤이라 푸는 순간 다 함께 있진 못했지만 너무너무 기뻤다.
>처음 플래티넘 문제를 풀었을 때 마냥 엄청 기뻐했다.
>
>이 문제는 오래오래 기억날 것 같다.
---
n개의 추가 주어질 때 n개의 추로 만들 수 없는 가장 작은 양의 정수를 찾는 문제 입니다
여러 아이디어를 고민하던 중 2진수를 사용해 접근하는 아이디어를 얻었습니다. `2^1 ~ 2^n` 까지 숫자가 다 있다면 `2^(n+1) - 1` 까지의 정수는 모두 만들 수 있다는 접근이였습니다.
하지만 위의 아이디어는 어디까지나 탐색해야할 범위를 줄이는 데에 그치는 정도였습니다. 아직 뭔가 부족했습니다.
여기서 조금 더 생각을 펼쳐본 결과 굳이 2진수가 아니더라도 `n개의 추`로 `1 ~ m` 까지의 …
> 7-yuyu0830

- dhlee777/dfs/적록색약.cpp
2시간
처음에 문제를 봤을때 `dfs`나` bfs` 를 통해 그림에서 단순히 `구역의 개수`를 구하는 문제인줄 알았으나  **`정상인일때의 탐색`과 `적록색약일때의 탐색 `이 두가지경우 가 존재했다.**  `적록색약의 특징은 r(빨강)과 g(초록)을 구분하지 못하는 것이다. `따라서 
그림의 색요소를 입력받을때 `적록색약의 탐색`을 위해  **r(빨강)을 g(초록)으로 바꿔서` color2배열`에 저장해준다.**
``` cpp
for (int i = 0; i < siz; i++) {          //color,clolor2배열에 그림을 입력받아 저장해준다.
cin >> line;
for (int j = 0; j < siz; j++) {
color[i][j] = line[j];
if (line[j] == 'R') color2[i][j] = 'G';     //적록색약을 위해 r을 g로 다 바꿔서 저장해준다.
else  color2[i][j] = line[j];
}
}
```
``` cpp
char color[100][100];   //정상인이 보는 그림의 색 요소
char color2[100][100];    //적록색약이 보는 그림의 색 요소
bool visited[100][100];   //정상인 그림의 방문여부
bool visited2[100][100];  //적록색약 그림의 방문여부
string line;             // 한줄 입력을 받기위한 스트링
int siz;                 //그림의 한 변의 길이
int coun = 0;            //정상인이 그림을 …
```
> 8-dhlee777

- seongwon030/bfs/결혼식.py
[결혼식](https://www.acmicpc.net/problem/5567)
1시간
1. 친구관계를 <code>2차원 리스트</code>에 저장한다.
ex) 만약 <code>1 3</code>이면 0부터 인덱스가 시작하므로 <code>arr[0][2]</code>와 <code>arr[2][0]</code>의 값을 1로 설정한다.
2. 방문 리스트를 <code>0으로 설정</code>한다.
3. 큐에 인덱스 0부터 넣고 방문처리를 한다.
-> <code>인덱스 0</code>은 상근이 자신이므로 <code>무조건 방문처리</code>
4. 큐가 빌 때까지 반복하고, 큐에서 노드를 하나씩 꺼내어 그것과 <code>연결된 노드가 방문이 안되었다면</code> 큐에 추가하고 방문처리한다.
5. BFS를 <code>시작 노드 0</code>으로 호출한다.
6. 방문순서가 2나 3일 때 카운트를 센다. <= 1번은 자기자신이고 2번은 친구, 3번은 친구의 친구이다. 
인접리스트로 간선을 구현해봤습니당
> 8-seongwon030

- yuyu0830/정렬/23970.cpp
[알고리즘 수업 - 버블 정렬 3](https://www.acmicpc.net/problem/23970)
1시간
`n`의 길이를 가진 `수열 a, b`가 주어진다. `a`를 버블 정렬 하려고 할 때, 중간에 `b`와 같아지는 순간이 생기는지 생기지 않는지 여부를 1, 0으로 출력하자
- 5 ≤ n ≤ 10,000
처음에는 이거 직접 버블 정렬 하면서 일일이 비교하면 시간이 말이 되나...? 싶었다. 버블 정렬은 무조건 `n * (n - 1) / 2` 번 연산할텐데? 싶어서 최대 경우의 수를 계산 해보니 약 5000만번... 여기에 매 정렬마다 10,000개씩 비교한다고 하면 무조건 시간 초과가 나겠다 싶었다.
일단 시간 초과가 나든 말든 한번 맨땅 헤딩부터 해보자는 마음으로 간단히 버블 정렬을 구현하고 매 번 배열을 처음부터 끝까지 비교하는 코드를 짰다.
```cpp
bool same() {
for (int i = 0; i < n; i++) 
if (arr[0][i] != arr[1][i]) return false;
return true;
}
while (rnd) {
// sort [0] to [ptr - rnd]
int a = arr[0][ptr];
int b = arr[0][ptr + 1];
arr[0][ptr] = min(a, b);
arr[0][ptr + 1] = max(a, b);
// if this index is last index in this round
if (++ptr == rnd) {
// next round
ptr = 0;
rnd--;
}
if (same()) {
// if arr is …
```
> 9-yuyu0830

- dhlee777/문자열처리/AC.cpp
[AC](https://www.acmicpc.net/problem/5430)
4시간30분
이 문제에서 배열의 원소들이 [1,2,3,5] 이런 형식으로 주어지는데 일단` 이 배열을 string 객체를 통해 입력받는다  `그리고 나서
이 문자열에서 숫자들을 분리해 내기  위해서  for루프문을 `string 사이즈` 만큼 돌리며 확인해준다. 이때  숫자가 10의자리 이상 일 수 있기때문에 그 수들을 저장해놓을` string객체를 하나 더 생성해준다.`
1.`"[","]"`의 경우 건너뛴다.
2.","가 나오기 전까지 문자들을 새로 생성한` string 객체에 계속합쳐준다.`
3.  `","가 나올경우  `그전까지  합쳐진 string 문자열들을` stoi()`를 통해 정수형으로 변환하고 `벡터에 push`해준다.
4. 마지막 문자는 , 표시가 없으므로 `제일 마지막에 따로 벡터에 push해준다`.
``` cpp
#include<vector>
#include<string>
#include<algorithm>
vector<int>v;
string a,b,nm;
ios_base::sync_with_stdio(false);
cin.tie(NULL);
int t,num;
bool flag = true;
cin >> t;
while (t--) {
flag = true;
cin >> a>>num>>b;
for (int i = 0; i <b.size(); i++) {
if (b[i] == '[' || b[i] == ']') …
```
> 9-dhlee777

- seongwon030/수학/연속 합.py
[연속 합](https://www.acmicpc.net/problem/2737)
대부분의 양의 정수는 적어도 2개 이상의 연속된 자연수의 합으로 나타낼 수 있다.
예를 들면 다음과 같다.
6 = 1 + 2 + 3
9 = 5 + 4 = 4 + 3 + 2
하지만, 8은 연속된 자연수 합으로 나타낼 수가 없다.
자연수 N이 주어졌을 때, 이 수를 적어도 2개 이상의 연속된 자연수의 합으로 나타낼 수 있는 경우의 수를 출력하시오.
1시간 30분
연속합이니까 어디까지 탐색을 해야할까 고민을 해봤다. <code>제곱근</code>부터 생각해봤는데 n=1800 일 때 제곱근이 42..xx였다. 근데 1800을 45로 나눈 몫이 40이고 , 그렇다면 40을 기준 양옆으로 22개씩 연속합을  계산해도 연속합에 포함되는 값이 턱없이 많이 남는다. 
나누는 수를 j , 나눈 몫을 center 라고 하면 <code>j는 연속합 구간의 정수의 개수</code>를 의미한다. <code>center는 그 구간의 중앙값</code>을 의미한다. center값은 소수점자리를 없애버리고 정수로 설정해줬다. <code>cnt는 경우의 수</code>다. (j//2 는 중앙값을 기준으로 양옆으로 더할 정수의 개수가 된다.)
1. j가 짝수일 때 -> center가 중앙값이 아니므로 연속합은 (center + center+1) x (j를 2로 나눈 몫) 
2. j가 홀수일 때 -> center가 중앙값이므로  center + center x 2 x (j//2) 
제일 중요한 것은 <code>어디까지 탐색해야 되는가</code> 인데 center …
> 10-seongwon030

- seongwon030/DP/합분해.py
[합분해](https://www.acmicpc.net/problem/2225)
3시간
이전에 풀었던 연속합 문제로 접근하니까 도저히 풀리지 않았다. n이 무조건 2개의 숫자의 합으로 나타나고 k개의 합으로 될 때까지 계속 나누어지므로 dp는 맞는 것 같았는데 풀다가 모르겠어서 다른 풀이를 참조했다.
일단 k를 1부터 , n은 0부터 해서 표를 그리면
|k\n|0|1|2|
|------|------|---|---|
|1|0|1|2|
|2|00|01,10|02, 11, 20|
|3|000|100, 001, 010|002, 011, 101, 020, 110, 200|
이렇게 되면 <code>dp[k][n] = dp[k-1][n] + dp[k][n-1]</code> 이라는 점화식이 나온다.
```python 
n,k = map(int,input().split())
mod = 1000000000
dp = [[0] * (n+1) for _ in range(k+1)] # 2차원 배열
dp [0][0] = 1 # 초기값 설정 
for i in range(1,k+1):
for j in range(n+1):
dp[i][j] = dp[i-1][j] + dp[i][j-1]
dp[i][j] = dp[i][j] % mod
print(dp[k][n])
```
복잡해보이지만 처음부터 차근차근... 점화식이 있는지부터 찾아보자
> 11-seongwon

- dhlee777/bfs/토마토.cpp
[토마토](https://www.acmicpc.net/problem/7569)
하루
기존의 `2차원배열의 토마토문제`는 풀어봤지만 이번에는 `3차원배열의 토마토 문제`를 풀게되었다.  달라진점은  탐색범위가 `기존에는 상,하,좌,우 4군데 `였다면 3차원배열에서는 `상,하,좌,우,위,아래 총 6군데`를 탐색해주어야한다. 이를 위해 좌표정보를 저장할
`tomato 구조체`를 선언해주었고 토마토의 상태를저장할 `tom[][][]배열`을 선언해주었다.
``` cpp
cin >> col >> row >> height;
for (int i = 0; i < height; i++) {
for (int j = 0; j < row; j++) {
for (int k = 0; k < col; k++) {
cin >> tom[i][j][k];
if (tom[i][j][k] == 1)         //익은토마토가 들어있으면
q.push(tomato(k, j, i));   //탐색시작점을위해 그 좌표를 큐에 넣는다.
}
}
}
```
tom배열에 상태를 저장할때는 `높이,행,열 순`으로 입력받는다. 여기서 만약 `토마토의 상태가 1이라면`  익은 토마토 이므로 `탐색 시작점을 위해 그 좌표를 큐에 넣어준다.`
``` cpp
void bfs() {
while (!q.empty()) {
tomato t = q.front();
q.pop();
for (int i = 0; i < 6; i++) {      //탐색범위(상,하,좌,우,위,아래)
int _x = t.x1 + x[i];
int _y = t.y1 + y[i];
int _z = …
```
> 10-dhlee777

- dhlee777/dp/1로만들기.cpp
[1로만들기](https://www.acmicpc.net/problem/1463)
1시간 30분
어떤수를 1로만드는데 걸리는 최소 연산횟수를 구하는 문제로 `dp`를 이용해서 풀어보았다.
연산의 종류는 총 3가지로
**1. 1을뺀다 
2. 3으로나누어떨어지면 3으로 나눈다. 
3. 2로나누어 떨어지면 2로 나눈다.**
우선  특정수 i(1<=i<=10^6) 에서의  1로만드는데 필요한 연산횟수를 저장하는 `배열 dp[i]`를 선언해준다.
그리고 i가 1일때 연산횟수는 0 , 2일때는 1, 3일때도 1이므로 초기값 설정을 해준다.(`dp[1]=0;dp[2]=1,dp[3]=1`)
그리고  1번 연산 `dp[i]=dp[i-1]+1` 을 `기본`으로 설정한 다음   i가 3으로 나누어떨어진다면 `dp[i] = min(dp[i], dp[i / 3] + 1)`  를 
통해 기본값과의 대소비교, i가 2로 나누어떨어진다면  `dp[i] = min(dp[i], dp[i / 2] + 1)` 를 통해 `최솟값`을 찾아준다.
``` cpp
int dp[1000001];
ios_base::sync_with_stdio(false);
cin.tie(NULL);
int num;
cin >> num;
dp[1] = 0;
dp[2] = 1;
dp[3] = 1;
for (int i = 4; i <= num; i++) {
dp[i] = dp[i - 1] + 1;
if (i % 3 == 0)
dp[i] = min(dp[i], dp[i / 3] + 1);
if (i % 2 == 0)
dp[i] = …
```
> 11-dhlee777

- dhlee777/README.md
- dhlee777/union-find/연결요소의개수.cpp
[연결요소의개수](https://www.acmicpc.net/problem/11724)
2시간
`정점과 간선들`이 주어지고  그래프내에서 몇개의 집합이 존재하는지 구하는 문제이다.` dfs,union-find` 두가지 방법 모두 이용해서 풀 수 있다고 생각하였고 첫번째로` union-find`를 이용하여 풀어보았다.
**1.간선의 양끝점을 입력받은 뒤 `unionn함수`를 통해 두 정점이 속한 집합끼리 합친다.
2.`for루프문`을 통해 모든정점들을 탐색하며 각정점의 루트 정점을 구한뒤 `set에 삽입`한다.
3.`set의 사이즈`가 구하고자하는 연결요소의 개수가 된다.**
set을 사용해준 이유는 각정점들의` 루트정점`이 `중복`될 수 있는데` set` 은 `중복원소를 받지 않기 때문`에  `set의 크기`로 영역의 개수를 구할 수 있다.
``` cpp
#include<vector>
vector<int>vec[1001];                   //간선의 정보를 나타내기위한 이차원벡터
int visited[1001];                         //방문여부저장위한 배열
int coun=0;
void dfs(int a) {
for (int i = 0; i < vec[a].size(); i++) {
if (!visited[vec[a][i]]) {
visited[vec[a][i]] = 1;
dfs(vec[a][i]);
}
}
} …
```
> 12-dhlee777

- yuyu0830/그리디/1826.cpp
[연료채우기](https://www.acmicpc.net/problem/1826)
20분
우리의 주인공 성경이는 수직선 상에서 0에서 출발해 L까지 가야한다. 연료가 제한되어있고, 중간중간 주유소가 있으며 주유소에서 채울 수 있는 연료의 양은 정해져있다. 주유소를 최대한 적게 방문하고 목표 지점까지 갈 수 있는 방법을 찾아보자
`주유소의 개수 n`이 주어진다. 이후 n개의 주유소 정보가 주어지는데 `시작 지점부터 주유소까지의 위치 a`, 주유소에서 얻을 수 있는 `연료의 량 b`가 주어진다.
이후 마지막 줄에 `목표 지점 L`과 `현재 연료 P`가 주어진다.
우선순위 큐를 이용하면 쉽게 풀 수 있는 문제였다. 
1. 현재 갈 수 있는 주유소를 우선순위 큐에 넣는다. (연료 많은 순)
2. 가장 연료를 많이 얻을 수 있는 주유소를 방문한다. (연료를 얻는다)
3. 목적지 도착 여부를 체크한다. 도착했다면 탐색 종료
4. 도착하지 못했다면 추가로 얻은 연료만큼 더욱 움직일 수 있으니 다시 1번부터 반복한다.
특별한 예외 케이스도 없었고 우선순위 큐를 쓰거나 정렬만 하면 되는 문제라 쉽게 풀렸던 것 같다. 이게 골드 2..?
> 11-yuyu0830

- dhlee777/dp/구간합구하기5.cpp
[구간합구하기5](https://www.acmicpc.net/problem/11660)
하루
``` cpp
int a[1025][1025];
int sum = 0;
int section_sum(int start_row, int start_col, int end_row, int end_col) {
for (int i = start_row; i <= end_row;i++) {
for (int j = start_col; j <=end_col; j++) {
sum += a[i][j];
}
}
return sum;
}
ios_base::sync_with_stdio(false);
cin.tie(NULL);
int size, cnt, start_row, start_col, end_row, end_col;
cin >> size >> cnt;
for (int i = 1; i <=size; i++) {
for (int j = 1; j <=size; j++) {
cin >> a[i][j];
}
}
for (int k = 0; k < cnt; k++) {
cin >> start_row >> start_col >> end_row >> end_col;
cout<<section_sum(start_row, start_col, end_row, end_col)<<"\n";
sum = 0;
}
}
```
첫번째풀이는` 배열`을통해 표를입력받고 무식하게 `구간합의 범위가 들어올때마다 for루프문을통해 구간의 범위를 다 탐색하며 합을 …
> 13-dhlee777

- seongwon030/README.md
- seongwon030/분할정복/피보나치수6.py
[피보나치 수 6](https://www.acmicpc.net/problem/11444)
3시간
알고리즘 분류에서 분할 정복 부분을 보다가 <code>행렬제곱으로 피보나치 수를 구하는 문제</code>가 있어서 풀어봤습니다. 
예전에 풀었던 [행렬제곱](https://www.acmicpc.net/problem/10830) 에서는 새로운 변수에 입력행렬을 저장해놓고
행렬곱으로 계속 갱신해주었는데 이 문제에서는 어떻게 기존값을 저장하면서 행렬곱을 진행해야 하는지 감을 잡기가 어려웠다.
피보나치 수열의 정의를 사용해서 <code>F(i+1) = F(i) + F(i-1)</code> 과 <code>F(i) = F(i) + 0</code>를 세웠다. 여기서 각 항을 상수와 F로 나누어 행렬의 곱으로 바꾸면 <br/>
이렇게 나타낼 수 있다. <br/>
마지막으로 점화식을 세우면 이런식이 나온다.
행렬제곱연산은 위의 행렬제곱문제에서 사용했던 함수를 그대로 사용했다. 
```python 
def matrixmult(A, B, mod):  # 행렬 곱 계산
n = len(A)
C = [[0] * n for _ in range(n)]
for i in range(n):
for j in range(n):
for k in range(n):
C[i][j] += A[i][k] * B[k][j]
C[i][j] %= mod
return C
```
거듭제곱 연산하기
```python
def matrixpow(M, N, mod):  # 행렬 거듭제곱 계산 (M의 N승)
n = len(M)
result = [[1 if i == j else …
```
> 13-seongwon030

- seongwon030/큐/가운데를말해요.py
[가운데를 말해요](https://www.acmicpc.net/problem/1655)
30분
- maxheap : 최대값에 바로 접근 가능
- minheap : 최소값에 바로 접근 가능
```
중앙값보다 작은 값은 maxheap에, 큰 값은 minheap에 저장한다 
```
1. <code>min_heap</code>과 <code>max_heap</code> 리스트를 만든다
2. 숫자를 입력받는다
3. 두 리스트 길이가 같다면 max_heap에 값을 넣는다
4. 다르면 이전에 최대 힙에 넣었으므로 min_heap에 넣는다
5. max_heap의 루트가 min_heap의 루트보다 크면, 값을 교환한다
6. 최대힙 루트에 음수를 붙여 출력한다
파이썬 힙 모듈은 최소힙만 지원한다. 그래서 최대힙을 구현하려면 힙에 음수로 숫자를 저장하여 루트를 계산해야 한다.
> 14-seongwon030

- seongwon030/큐/중앙값구하기.py
[중앙값 구하기](https://www.acmicpc.net/problem/2696)
1시간 
교황형님이 추천해주신 문제 바로 꿀꺽했습니다. 
[여기](https://github.com/AlgoLeadMe/AlgoLeadMe-8/pull/58)에서 쓴 min_heap, max_heap을 이용했습니다.
``` python
def push_num(num):
if len(max_heap) == len(min_heap):
heapq.heappush(max_heap, -num)
else:
heapq.heappush(min_heap, num)
if min_heap and -max_heap[0] > min_heap[0]:
min = heapq.heappop(min_heap)
max = -heapq.heappop(max_heap)
heapq.heappush(max_heap, -min)
heapq.heappush(min_heap, max)
```
1. 홀수일때만 중앙값은 짝수일 때 <code>n//2</code>, 홀수일 때 <code>n//2+1</code>
2. 중앙값인 <code>-max_heap[0]</code>을 인덱스 k가 짝수일 때 (개수가 홀수개일 때) 리스트 re에 넣는다.
3. 마지막에 n이 짝수면 또한 <code>-max_heap[0]</code>를 re에 넣는다.
4. re를 돌면서 cnt를 1씩 더한다.
5. 10으로 나눈 나머지가 0일 때 줄바꿈을 해 준다.
> 15-seongwon030

- yuyu0830/수학/17387.cpp
[선분 교차 2](https://www.acmicpc.net/problem/17387)
3일 (무려 67트..)
(아찔)
선분 2개가 (x1, x2), (y1, y2), (a1, a2), (b1, b2) 의 형태로 주어진다. 이 때 이 선분이 교차하는지 교차하지 않는지 판단하자. (점에서 만나는 경우도 겹치는 것이다.)
사실 처음 봤을때 너무 쉬워보였다. 다양한 방법이 떠올랐고, 예외도 그렇게 많이 떠오르진 않았다. 해결 방식은 **"점 x, y를 지나는 `직선 P`와 점 a, b를 지나는 `직선 Q`의 교차점이 T일 때, T가 점 x, y를 잇는 `선분 U` 위에 있으면서 동시에 점 a, b를 잇는 `선분 S` 위에 있으면 교차한다"** 라는 풀이다. 즉 선분을 직선으로 연장한 뒤 교차점을 찾고, 해당 교차점이 선분 위에 있는지 확인하는 방식이였다.
풀이 방식에 대한 로직은 간단했다. 점 x, y를 지나는 `직선 P의 기울기 g`는 `y의 증가량 / x의 증가량 = (y2 - y1) / (x2 - x1)` 이고, `y 절편 i`는 `y = mx + b, b = y1 - (y2 - y1) / (x2 - x1) * x1` 가 된다. 
위 공식을 통해 `직선 P`와 `직선 Q`의 기울기와 절편을 구했다면 해당 두 공식의 교차점을 찾으면 된다. `P = Q`가 되는 점을 찾으면 되기 때문에 `P = mx + a = nx + b = Q` 라고 공식을 세우고 각각 기울기와 절편을 대입한 뒤, 연립 방정식으로 식을 풀면 `P = Q` 가 되는 `직선의 교차점 T`를 구할 수 있다.
`교차점 T`를 구했으니 이제 선분 …
> 14-yuyu0840

- yuyu0830/README.md
- yuyu0830/수학/2166.cpp
[다각형의 면적](https://www.acmicpc.net/problem/2166)
5시간
n각형의 꼭지점 n개의 좌표 (x, y) 가 다각형을 이루는 순서대로 주어진다. 이 다각형의 면적을 구하자
- -100,000 <= x, y <= 100,000
- 3 <= n <= 10,000
요즘 푸는 문제마다 왜 다 이 꼴인지 모르겠다..
`다각형을 포함하는 x, y축에 평행한 가장 작은 직사각형`을 그린 뒤, 다각형에 포함되지 않는 범위를 하나씩 빼나가는 방식이다.
즉 아래의 파란 다각형에 대해 주황색 부분을 빼서 전체의 넓이를 구하는 방식이다.
다각형의 한 변을 포함하며 다각형의 내부에 포함되지 않는 삼각형(초록색)을 그려 변의 개수 만큼 빼주는 방식이다.
<details>
<summary><h3>이미지 예제</h3></summary>
</details>
그렇게 바깥 삼각형을 모두 빼고 나면 다각형의 넓이만 남게 된다는 풀이였다!
여기서 어려웠던 점은 `다각형의 각 변`과 `큰 사각형의 어느 꼭지점` 을 연결해야하는지 판단해야하는 부분이였다.
이 부분은 모든 꼭지점을 x 기준으로 정렬한 뒤 각 꼭지점을 시계방향으로 순회하는데, 탐색하는 꼭지점이 사각형의 각 변에 닿으면 다음 꼭지점과 이어주는 방식으로 구현했다.
<details>
<summary><h3>이미지 예제</h3></summary>
</details>
<details>
<summary><h3>소스코드</h3></summary>
```cpp
#include <vector>
#include <algorithm> …
```
> 15-yuyu0830

- yuyu0830/README.md
- yuyu0830/자료구조/4386.cpp
[별자리 만들기](https://www.acmicpc.net/problem/4386)
5-10분!
`별의 위치 (float x, float y)` 가 n개 주어진다. 모든 별을 포함하면서 그 길이가 가장 짧은 별자리를 그려보자!
너무 간단한 최소 신장 트리 문제.. 날먹 느낌이 조금 나지만 최근에 3문제 푸는데 100번 가까이 틀리고 멘탈이 갈려서 살짝 쉬어가는 느낌으로 풀어봤다. 기존에 MST 문제를 풀때 썼던 Union-Find 알고리즘을 사용해 구현했다.
별의 위치가 n개 주어지면 각 별끼리 이을 수 있는 선분의 개수는 `n * (n - 1) / 2` 가 된다. 하지만 별의 개수가 최대 100개 밖에 안되기 때문에 모든 선분을 고려하는 알고리즘을 짰다.
우선 각 별의 위치를 전부 받은 뒤, 각 별마다 나갈 수 있는 선분의 경우의 수를 모두 저장해 우선순위 큐에 저장한다.
```cpp
// 별 위치 저장
for (int i = 0; i < n; i++) {
float a, b; cin >> a >> b;
arr[i] = point(a, b);
}
// 각 별마다 이을 수 있는 모든 선 우선 순위 큐에 저장
// 우선 순위 큐는 선분의 길이를 기준으로 정렬
for (int i = 0; i < n; i++) 
for (int j = i + 1; j < n; j++) 
q.push(edge(i, j));
```
이후에 Union-Find를 사용한 MST 알고리즘을 적용하면 완성!
```cpp
#include <queue>
#include <math.h>
#define …
```
> 16-yuyu0830

- InSange/README.md
- InSange/그래프/2285_Maximum_Total_Importance_of_Roads.cpp
[Miaximum Total Importance of Roads](https://leetcode.com/problems/maximum-total-importance-of-roads/)
1시간
각 노드에 연결지점 `roads`를 통해서 각 노드 `n`개에 해당하는 2차원 배열을 만들어준다.
노드의 개수가 많으면 높은 점수를 차례로 부여한다. `n`, `n-1`, `n-2` ... `0` 이런식으로..
그리고 해당 간선의 합을 `answer`에 차근차근 저장해주면 되는데
계산한 노드를 `unordered_map`에다가 넣어서 두 노드가 이미 계산된 값이라면 계산을 수행하지 않는 식으로 진행하려다보니 필요 메모리와 코드가 너무 지저분해졌다.
사실 연결된 노드를 각각 따로 계산할 필요 없이 연결된 `degree`만큼 부여된 점수를 연산해주면 되는 것이었다.
위에서 말한대로 차수와 해당 인덱스를 우선순위 큐를 통해 정렬 시켜주고 높은 차수(`degree`)를 지닌 노드를 하나씩 꺼내 점수를 매기고 degree만큼 곱해서 바로 해결해주는 식으로 바꾸었다.
```c++
public:
long long maximumImportance(int n, vector<vector<int>>& roads) {
vector<vector<int>> conn;   // road
priority_queue<pair<long long, int>> pq;  // connect degree first: degree, second: index
long long answer = 0;
conn.assign(n, …
```
> 16-InSange

- InSange/README.md
- InSange/문자열/6_Zigzag Conversion.cpp
[Zigzag Conversion](https://leetcode.com/problems/zigzag-conversion/)
1시간
문자열을 방문하는데 각자 행에 해당하는 배열에다가 하나씩 집어넣는 식으로 채워준다.
0번째 행과 N-1번째 행일 때마다 추가해주는 방향을 전환시켜준다.
```c++
public:
string convert(string s, int numRows) {
if(numRows <= 1 || s.size() <= numRows) return s;
vector<string>v(numRows, "");
int i, j, dir;
j = 0;
dir = -1;
for(i = 0; i < s.size(); i++)
{
if(j == numRows - 1 || j == 0) dir *= -1;
v[j] += s[i];
if(dir == 1) j++;
else j--;
}
string answer;
answer = "";
for(auto c : v)
{
answer += c;
}
return answer;
}
};
```
처음에 접근할 때 규칙이 있을 것이라고 판단하였는데 오히려 더 단순히 왔다갔다하면 되는 부분이라 조금 헷갈린 점외에는 없었다. 방향만 잘 잡으면 무난한 정도?
> 17-InSange

- yuyu0830/README.md
- yuyu0830/위상정렬/1005.cpp
[ACM Craft(1005)](https://www.acmicpc.net/problem/1005)
1일..? 중간에 한번 관뒀다 다시 풀었슴다
테스트 케이스가 T개 주어진다. 각 테스트 케이스에선 건물 n개와 각 건물을 짓는데 걸리는 시간 D1 ~ Dn, 건물 끼리의 관계 k개가  주어질 때, 그 중 w번째 건물을 짓는데 걸리는 최단 시간을 출력하자.
각 건물은 선행 조건이 주어지는데, 선행 조건으로 주어진 건물을 모두 건설한 경우에 해당 건물을 짓기 시작할 수 있다.
<details>
<summary><h4>위상정렬 정리</h4></summary>
우선 위상정렬 알고리즘을 알아보자. <br><br>
위상 정렬은 방향이 있고 사이클이 반복하지 않는 DAG(Directed Acycle Graph) 을 정렬할 때 사용할 수 있다. 정렬이기 때문에 시작 지점이 있어야하고, 사이클이 있는 경우에는 시작 지점을 특정할 수 없기 때문에 사이클이 없는 경우에 대해 사용할 수 있다.<br><br>
큐와 스택을 이용한 풀이가 가능한데 이번 풀이에선 큐를 사용할 예정이다.
1. 각 노드에 대해 진입 차수를 구한다.
2. 진입 차수가 0인 노드를 골라 큐에 넣는다
3. 방금 고른 노드에서 연결된 edge를 모두 제거한다.
4. 모든 노드가 사라질 때까지 1번을 반복한다.
완성! 이 때 큐에 들어있는 노드의 순서가 위상정렬된 순서가 된다!
</details>
<br>
건물을 짓는 순서는 위상정렬을 했을 때 나오는 순서대로 건설하면 된다. 아래 예시를 보자
당연하지만 단순 위상정렬한 대로 건설 시간을 더하면 안된다. 같이 진행될 …
> 17-yuyu0830

- seongwon030/최소스패닝트리/정복자.py
[정복자](https://www.acmicpc.net/problem/14950)
1시간
<details>
<summary>문제</summary>
서강 나라는 N개의 도시와 M개의 도로로 이루어졌다. 모든 도시의 쌍에는 그 도시를 연결하는 도로로 구성된 경로가 있다. 각 도로는 양방향 도로이며, 각 도로는 사용하는데 필요한 비용이 존재한다. 각각 도시는 1번부터 N번까지 번호가 붙여져 있다. 그 중에서 1번 도시의 군주 박건은 모든 도시를 정복하고 싶어한다.
처음 점거하고 있는 도시는 1번 도시 뿐이다. 만약 특정 도시 B를 정복하고 싶다면, B와 도로로 연결된 도시들 중에서 적어도 하나를 정복하고 있어야 한다. 조건을 만족하는 도시 중에서 하나인 A를 선택하면, B를 정복하는 과정에서 A와 B를 연결하는 도로의 비용이 소모된다. 박건은 한번에 하나의 도시만 정복을 시도하고 언제나 성공한다. 한 번 도시가 정복되면, 모든 도시는 경계를 하게 되기 때문에 모든 도로의 비용이 t만큼 증가하게 된다. 한 번 정복한 도시는 다시 정복하지 않는다.
이때 박건이 모든 도시를 정복하는데 사용되는 최소 비용을 구하시오.
첫째 줄에 도시의 개수 N과 도로의 개수 M과 한번 정복할 때마다 증가하는 도로의 비용 t가 주어진다. N은 10000보다 작거나 같은 자연수이고, M은 30000보다 작거나 같은 자연수이다. t는 10이하의 자연수이다.
M개의 줄에는 도로를 나타내는 세 자연수 A, B, C가 주어진다. A와 B사이에 비용이 C인 도로가 있다는 뜻이다. A와 B는 N이하의 서로 다른 자연수이다. C는 10000 이하의 …
> 18-seongwon030

- InSange/README.md
- InSange/문자열/1598_Crawler Log Folder.cpp
[Crawler Log Folder](https://leetcode.com/problems/crawler-log-folder/)
15분
1. Log 내역이 `../`일 경우 현재의 높이 값에 맞게 설정 - 0보다 클시에 -1
2. `./`는 작성 불필요
3. 이외의 값들은 모두 높이 증가
```c++
public:
int minOperations(vector<string>& logs) {
int height;
height = 0;
for(auto str : logs)
{
if(str[0] != '.') height++;
else if(str == "../") height = (height ? height - 1 : 0);
}
return height;
}
};
```
리트코드에서는 데일리 미션을 제공해준다.
난이도는 날에 따라 천차만별인데 오늘은 유독 쉬운 난이도..?
> 18-InSange

- seongwon030/유니온파인드/집합의표현.py
[집합의 표현](https://www.acmicpc.net/problem/1717)
15분
최소 신장 트리에서 사용한 알고리즘과 거의 동일해서 푸는데 많이 걸리지 않았습니다.
1.  0일 때는 <code>union</code>연산을 진행한다.
```python
def union(x,y):
x,y = find(x),find(y)
if x<y:
parent[x] = y
else:
parent[y] = x
```
> 각 원소의 루트 노드를 찾아 비교하면서 두 원소를 하나로 합치는 합집합 연산
2. 1일 때는 두 원소가 한 집합에 포함되는지 확인한다.
```python
def find(x):
if x!=parent[x]:
parent[x] = find(parent[x])
return parent[x]
```
> 루트노드가 같으면 한 집합에 포함되므로 <code>YES</code>를 출력, 아니면  <code>No</code>를 출력한다.
> 20-seongwon030

- yuyu0830/README.md
- yuyu0830/재귀/1949.cpp
드디어 상위 100문을 골드로 채웠습니다! 다음은 플레..?
[우수 마을](https://www.acmicpc.net/problem/1949)
4 시간
---
N개의 마을로 이루어진 나라가 있다. 편의상 마을에는 1부터 N까지 번호가 붙어 있다고 하자. 이 나라는 트리(Tree) 구조로 이루어져 있다. 즉 마을과 마을 사이를 직접 잇는 N-1개의 길이 있으며, 각 길은 방향성이 없어서 A번 마을에서 B번 마을로 갈 수 있다면 B번 마을에서 A번 마을로 갈 수 있다. 또, 모든 마을은 연결되어 있다. 두 마을 사이에 직접 잇는 길이 있을 때, 두 마을이 인접해 있다고 한다.
이 나라의 주민들에게 성취감을 높여 주기 위해, 다음 세 가지 조건을 만족하면서 N개의 마을 중 몇 개의 마을을 '우수 마을'로 선정하려고 한다.
'우수 마을'로 선정된 마을 주민 수의 총 합을 최대로 해야 한다.
마을 사이의 충돌을 방지하기 위해서, 만일 두 마을이 인접해 있으면 두 마을을 모두 '우수 마을'로 선정할 수는 없다. 즉 '우수 마을'끼리는 서로 인접해 있을 수 없다.
선정되지 못한 마을에 경각심을 불러일으키기 위해서, '우수 마을'로 선정되지 못한 마을은 적어도 하나의 '우수 마을'과는 인접해 있어야 한다.
각 마을 주민 수와 마을 사이의 길에 대한 정보가 주어졌을 때, 주어진 조건을 만족하도록 '우수 마을'을 선정하는 프로그램을 작성하시오.
---
첫째 줄에 정수 N이 주어진다. (1 ≤ N ≤ 10,000) 둘째 줄에는 마을 주민 수를 나타내는 N개의 자연수가 빈칸을 사이에 두고 주어진다. 1번 마을부터 N번 마을까지 …
> 19-yuyu0830

- InSange/README.md
- InSange/스택/1190_Reverse Substrings Between Each Pair of Parentheses.cpp
[reverse-substrings-between-each-pair-of-parentheses](https://leetcode.com/problems/reverse-substrings-between-each-pair-of-parentheses/)
3시간
문자열 `s`가 주어진다. `s`는 소문자와 `(`, `)`로 이루어진 문자열이다.
각 괄호는 Layer와 같은 역할을 한다.
처음에는 문자열이 순서대로 나오지만 `(`가 시작되는 순간 해당 Layer에 있는 문자열들은 순서가 뒤집힌다.
1. `)`를 제외한 문자들을 스택에다가 집어넣는다.
2. `)`를 만났을 때 스택에 존재하는 모든 문자를 `word`변수에 넣고 다시 스택에다가 집어 넣는다. (=> 문자열을 한번 뒤집음)
3. 정답에다가 추가한다. 
단, 주의해야할 점
s = "(abcd)"
stack = a <- b <- c <- d 로 저장된다.
`)`를 만나게되면
word = dcba
stack = d<-c<-b<-a로 저장된다.
출력할때 한번 더 뒤집어주면 d c b a로 출력이 되게 된다! => ans = stack->top() + ans;
```c++
#include <stack>
public:
string reverseParentheses(string s) {
stack<char> st;
string ans;
string word;
ans = "";
for (char c : s)
{
if (c == ')')
{
word = "";
while …
```
> 19-InSange

- seongwon030/dfs/트리.py
[트리](https://www.acmicpc.net/problem/1068)
1시간
<code>리프 노드</code>란 자식이 없는 노드이므로 <code>삭제노드</code>가 정해졌을 때 해당 노드를 기준으로 해서 자식 노드를 재귀적으로 없애면 된다.
1. <code>삭제노드</code>의 값을 노드 번호와 겹치지 않는 값으로 설정한다.
2. 노드 개수만큼 반복하며 노드의 값이 이전에 설정한<code>의미 없는 값</code>이라면 1번으로 돌아가 같은 과정을 반복한다.
3. 위 과정을 반복하면서 삭제노드의 자식노드까지 모두 없앤다.
```python
def dfs(node):
k[node] = -2
for i in range(n):
if node == k[i]:
dfs(i)
dfs(del_node)
```
모든 노드를 순회하며 값이 <code>의미 없는 값</code>이 아니어야 하고 노드 또한 노드 리스트에 없어야 한다.
```python
cnt = 0
for j in range(n):
if k[j] != -2 and j not in k:
cnt+=1
print(cnt)
```
dfs에 대해 파 볼 예정입니다.
> 21-seongwon030

- yuyu0830/LIS/14003.cpp
- yuyu0830/README.md
[가장 긴 증가하는 부분 수열 5](https://www.acmicpc.net/problem/14003)
아주 오래... 틈틈히 풀어서 체감상 2주..? 모으면 한 3~4시간
`수열 A` 가 주어진다. 가장 긴 증가하는 수열, 즉 LIS의 크기를 구한 뒤 LIS를 하나 출력하자!
- 수열 A의 크기 N : (1 ≤ N ≤ 1,000,000)
- 수열 A를 이루고 있는 Ai : (-1,000,000,000 ≤ Ai ≤ 1,000,000,000)
---
보다시피 조건을 조금씩 바꿔서 꿀빨 수 있는 문제 라인업이다. 5번 문제는 지금까지 조건을 모두 합쳤다. 각 조건은 아래와 같다.
<br>
1. `수열의 크기`가 **1,000,000** 이다.
- LIS 배열 탐색 시간을 O(n log n) 을 만들어야 한다. ([이전 풀이 참고](https://github.com/AlgoLeadMe/AlgoLeadMe-8/pull/52))
2. `Ai`가 **음수를 포함**한다.
- 배열의 값을 최저한도로 초기화 해두거나 vector를 써서 빈 배열의 경우를 처리한다.
3. `Ai의 범위`가 **1,000,000,000** 까지 늘어난다.
- 이진 탐색을 통해 탐색 시간도 O(n log n) 을 만들어야 한다.
4. `LIS`를 하나 출력해야한다.
- 1번 조건을 위해 배열 탐색 시간을 O(n log n) 으로 만들면 값을 항상 갱신하기 때문에 LIS를 만들기 위해서는 추가적인 방법이 필요하다.
<br>
1, 2, 3번 조건은 크게 어렵지 않으니 4번 조건 해결만 보자
문제가 되는 상황은 다음과 같은 상황이다. 
`수열 …
> 20-yuyu0830

- InSange/README.md
- InSange/그리디/1605_Find Valid Matrix Given Row and Column Sums.cpp
- InSange/스택/1190_Reverse Substrings Between Each Pair of Parentheses.cpp
- InSange/스택/2751_Robot Collisions.cpp
[Find Valid Matrix Given Row and Column Sums](https://leetcode.com/problems/find-valid-matrix-given-row-and-column-sums/)
8시간
입력값으로 각 행의 요소들을 더한 값과 각 열의 요소들을 더한 값이 주어진다.
Input: rowSum = [3,8], colSum = [4,7]
rowSum[0] 번째 행의 요소들을 모두 더한 값은 3이 되고
colSum[0] 번째 열의 요소들을 모두 더한 값은 4가 된다.
와 같이 구성이 되어야 한다.
행 인덱스 `rIndex`와 열 인덱스 `cIndex`가 0부터 시작해서 `ans` 행렬에 해당하는 부분 `ans[rindex][cindex]`가 위치하는 부분의 값 중 최소 값을 넣으면서 하면 되지 않을까였다.
최소값을 배치한 만큼 `rowSum`과 `colSum`에서 빼서 행과 열의 인덱스를 점차 증가시키는 방식으로 접근하였으나 런타임 에러가 발생하였다.
에러는 힙 버퍼 오버플로우로 최소값을 구할 때 인덱스가 `rowSum`과 `colSum`을 벗어나는 상황이 발생한 것이었다.
여기서 문득든 생각은 우리가 만드는 행렬은 모든 수를 써서 행과 열들의 합들을 일치시켜줘야하는게 아닌가? 였고 예외사항들을 찾다보니 시간이 오래걸리게 되었다.
`rowSum`과 `colSum`을 다 탐색하되 배열에 값이 남을 경우 다 채워주는 방식으로 가기로하였다.
1. 해당 행과 열 인덱스 `rIndex`, `cIndex`의 값들을 통해 최소값을 파악하고 업데이트한다.
2. `rowSum`과 …
> 21-Insange

- InSange/DP/1105_FillingBookcaseShelves.cpp
- InSange/README.md
- InSange/그리디/1605_Find Valid Matrix Given Row and Column Sums.cpp
- InSange/스택/2751_Robot Collisions.cpp
- InSange/슬라이딩 윈도우/2134_Minimum Swaps to Group All 1's Together 2.cpp
[Filling Bookcase Shelves](https://leetcode.com/problems/filling-bookcase-shelves/)
12시간
입력으로 주어진 books 2차원 배열의 요소는 첫 번째 요소로 너비를, 두 번째 요소로 높이를 지닌다.
순서대로 책을 선반에 놓되 각 선반에 놓이는 책은 입력으로 주어진 `shelfWidth`보다 작거나 같아야 놓을 수 있다.
그렇게 해서 배치를 하였을 때 최소의 높이를 구하라.
순서대로 차곡차곡 dp배열 `heightArr`에 넣어주되 현재 값에서 이전 값들의 dp배열 요소에 방문해준다.
즉 비교 방식은 아래와 같이 이루어진다.
1. `i-1`번째 요소의 최소 높이 값을 저장하는 `heightArr[i]`에다가 이전의 최소 값 `heightArr[i-1]`과 현재 요소 `i-1`의 높이를 더한 값으로 초기화 해준다.
2. 즉, 각기 다른 선반에 놓았을 때 구해지는 높이이다.
3. `i-2`번째 요소부터 0번째 요소까지 비교해 줄 것이다.
4. 우선 현재 `i-1`번째 너비와 `j-1`번째 요소의 너비를 합했을 때 `shelfWidth`보다 크면 바로 비교를 종료해준다.
5. 조건이 충적될 경우. 추가해준 대상 `j-1`번째 요소의 높이와 현재 최대 높이를 지니고 있는 변수 `height`값을 갱신해준다. 즉, 같은 선반에 위치할 경우 높은 `height`의 값으로 바뀌면서 해당 선반이 차지하는 높이를 가리키게 된다.
6. 높이 값을 구했을 때 같은 선반에 위치 시키는게 최소인지 (그냥 `heightArr[i]`), 아니면 각기 다른 선반으로 …
> 22-InSange

- InSange/BFS/1068.cpp
- InSange/DP/1105_FillingBookcaseShelves.cpp
- InSange/README.md
- InSange/그리디/1605_Find Valid Matrix Given Row and Column Sums.cpp
- InSange/스택/2751_Robot Collisions.cpp
- InSange/슬라이딩 윈도우/2134_Minimum Swaps to Group All 1's Together 2.cpp
[트리](https://www.acmicpc.net/problem/1068)
4시간
노드의 개수 `N`개가 주어지고 각 노드의 부모를 가리키는 인덱스 번호가 N개 주어진다.
루트 노드의 부모는 -1이다.
그리고 마지막으로 지우고자 하는 노드의 번호가 주어지며 해당 노드의 자식 노드도 다 없어진다.
각 노드에는 자식들의 인덱스를 저장할 배열과 부모 노드의 주소를 저장할 변수를 지니고 있으며 추가로 리프노드인지 확인할 수 있는 불리언 변수도 지니고 있다.
해당 노드는 구조체로 이루어져 있으며 각 노드들에 대한 주소는 배열 `nodes`에 저장된다.
지우고자 하는 노드를 입력받으면 해당 노드가 루트 노드인지 파악하여 루트 노드가 아닐 경우 해당 노드의 부모 노드를 업데이트 시켜준다.
```c++
#include <vector>
#include <queue>
struct Node
{
Node()
{
parent = nullptr;
leafNode = true;
}
vector<int> childs;
Node* parent;
bool leafNode;
};
vector<Node*> nodes;
int N, ans = 0, rIndex;
void NodeUpdate(Node* curNode)
{
for (auto child : curNode->childs)
{
if (nodes[child] != nullptr)
{
curNode->leafNode = false;
return;
}
}
curNode->leafNode = true;
}
void …
```
> 24-InSange

- yuyu0830/LCS/9252.cpp
- yuyu0830/README.md
[LCS 2](https://www.acmicpc.net/problem/9252)
2시간
골드 4...? 이게..?
---
<br>
<br>
예전에 [LCS 문제](https://www.acmicpc.net/problem/9251)를 푼 적이 있어서 해당 풀이를 참고했다. 기존 문제는 LCS의 길이만 구하면 되기에 2차원 DP 배열을 이용해 `1번 문자열의 i번째 char, 2번 문자열의 j번째 char로 만들 수 있는 LCS의 최대 길이`를 저장해 사용했다.
`str1[i]`와 `str2[j]` 가 같다면 LCS를 1 늘릴 수 있다는 것이기 때문에 `str1[i]` 와 `str2[j]` 의 이전 문자열 중 최대 값, 즉 `dp[i - 1][j - 1]` 의 값에 1을 더하면 된다.
만약 `str1[i]` 와 `str2[j]` 가 다르다면 `str1[i]` 혹은 `str2[j]` 둘 중 하나를 사용한 최대 값, 즉 `dp[i][j - 1]`, `dp[i - 1][j]` 중 큰 값을 쓰면 된다.
i - 1, j - 1을 다루기 때문에 out of bound 에러를 방지하기 위해 배열을 1씩 미룬 뒤, i나 j값이 0인 경우는 값을 0으로 채웠다.
<br>
예시를 보자
표를 여기까지 채웠고 빨간 박스를 채워야할 차례다. `1번째 문자열의 5번째 문자 k`와 `2번째 문자열의 5번째 문자 A`를 비교하고 있다. 이 둘은 서로 다르기 때문에 각각 dp[i][j - 1]과 dp[i - 1][j] 중에 큰 값을 사용하면 된다.
다음 칸을 보자
이번엔 비교하는 두 문자 모두 k로 같기 때문에 `dp[i - 1][j - …
> 23-yuyu0830

- yuyu0830/DP/1562.cpp
- yuyu0830/README.md
[계단 수](https://www.acmicpc.net/problem/1562)
3~4시간
---
당최 어떻게 접근해야할지 갈피가 잡히지 않았다..
<br>
<br>
계단수는 항상 각 자리수가 1 차이가 나야한다. 현재 수가 `345` 라고 하면 앞에 2 혹은 4를 붙인 `2345`, `4345` 와 뒤에 4 혹은 6을 붙인 `3454`, `3456` 가 올 수 있다. 이 점에 착안해 `현재 수열의 길이 i`, `수열의 시작 수 j`, `수열의 끝 수 k` 를 저장하는 DP 배열로 해결하려 했다.
현재 수열이 `j로 시작해 k로 끝나는 i 길이의 수열`이라면 `시작 수가 j - 1 혹은 j + 1 이면서 k로 끝나는 i + 1 길이의 수열`과 `시작 수가 j 이면서 k - 1 혹은 k + 1로 끝나는 i + 1 길이의 수열`을 만들 수 있다.
<br>
이 방법을 제출해보진 않았지만 당장 풀다가 겹치는 수를 해결할 수 없다는 결론에 도달했다. 
`수열 2345`와 `수열 1234`가 있을 때, 두 수열 모두 `12345` 라는 수열을 만들 수 있기 때문이다. 따라서 수열을 증가하는 방향을 한 방향으로 제한할 필요가 있다고 생각했다.
<br>
<br>
진짜 도저히 1도 모르겠어서 블로그 풀이를 참고했다. ([링크](https://velog.io/@js43o/%EB%B0%B1%EC%A4%80-1562%EB%B2%88-%EA%B3%84%EB%8B%A8-%EC%88%98))
정답 풀이는 비트마스킹을 이용한다. 현재 수열이 어떤 수들을 거쳐왔는지를 비트마스킹을 통해 표현할 수 있다. 0 ~ 9까지의 숫자가 1개 이상 …
> 22-yuyu0830

- InSange/BFS/1068.cpp
- InSange/BFS/310_Minimum Height Trees.cpp
- InSange/DP/1105_FillingBookcaseShelves.cpp
- InSange/README.md
- InSange/수학/840_Magic Squares In Grid.cpp
- InSange/슬라이딩 윈도우/2134_Minimum Swaps to Group All 1's Together 2.cpp
[Minimum Height Trees](https://leetcode.com/problems/minimum-height-trees/)
1시간
`n`개의 노드가 주어지며 각 노드는 단일 경로로 되어 있다. 즉, 노드끼리 하나의 간선만 존재한다.
그리고 트리의 특성 상 순환이 존재하지 않는다.
루트 노드에서 자식 노드까지 도달하는 것은 트리의 높이이다.
주어진 노드들 중에서 임의로 루트를 지정했을 때 최소 높이를 가지는 노드들의 출력하라.
문제만 읽었을 때 보면 모든 노드들 중에서 임의의 노드를 하나씩 선택해가면서 트리의 높이가 최소인 것들을 모으면 되겠다! 로 접근하면 시간 초과가 발생할 것이다.
그럼 어떻게 하면 좋을까?
만약 노드의 개수 `n`개가 2라면 트리의 높이는 무조건 1일 수 밖에 없다. 서로 연결해주는 간선이 한 개 뿐이기 때문이다.
그럼 노드의 개수가 3이라면? 아마 0-1-2 이런 식으로 될 것이고 이 때 역시 중간 1을 선택해주면 높이가 1이 될 것이다.
그럼 만약 4라면? 0-1-2-3 으로 되어 있다면 1과 2를 선택했을 때 높이가 2로 최소가 될 것이다.
문제 예시로 주어진 것을 확인해보자.
그림을 보자마자 알겠지만 1에 모든 노드들이 연결되어 있기 때문에 1이 최소 높이를 만든다는 것을 확인할 수 있다.
여기서 조금만 다르게 접근해보면 루트 노드에 연결되는 노드들은 모두 자식노드들로써 간선이 한 개라는 것을 파악할 수 있다.
즉, 두 개 이상의 노드들이 존재할 때 간선이 한 개 뿐인 자식 노드들을 제거해나간다면 결국 간선의 개수가 가장 적게 되는 소수의 노드들이 생존할 것이라는 …
> 25-InSange

- .vscode/settings.json
- yuyu0830/README.md
- yuyu0830/구현/12100.cpp
- yuyu0830/수학/2023.cpp
[신기한 소수](https://www.acmicpc.net/problem/2023)
50분
---
첫 접근이 바로 떠오르지가 않았다. 어떤 식으로 풀어야할까? 8자리 소수를 어떻게 처리해야할까 고민을 좀 했다. 
처음 생각한건 자릿수 별로 소수를 정리하는 것이였다. 정리한 뒤 n자리수가 되도록 조합해서 정리하는 것이었다.
하지만 그렇게 하면 8자리의 경우 8자리 소수까지 모두 구할 필요가 있었다. 각 자리수 별로 O(log n) 만큼 구해야 하니까 O(n log n) 이 되고, 99,999,999 에 대한  n log n 이기 때문에 2초 안에 풀 수가 없다.
애초에 메모리도 4MB기 때문에 저걸 다 저장하면서 할 수가 없다..
<br>
그 다음 떠오른 생각은 앞자리부터 소수인지 확인하며 수를 확장하는 방법이다.
문제에서는 4자리, 3자리, 2자리 이렇게 줄어들며 소수인지 확인하기에 바로 떠오르지 않았지만 반대로 1자리부터 소수인지 확인한다면 확인해야하는 수의 범위가 확연히 줄어든다.
맨 앞자리 수부터 소수인지 확인한 뒤, 소수인 수를 vector에 저장한다. 이렇게 하면 vector에 있는 수들은 전부 소수가 된다.
vector에 있는 수들을 하나씩 꺼내서 맨 뒤에 0~9까지 숫자를 붙여본 뒤, 다시 소수인지 확인하며 원하는 n의 자리까지 확인해보면 된다.
이렇게 하면 확인해야하는 수의 범위가 아주아주 줄어든다. 특히 수가 커질 수록 소수일 가능성이 낮아지므로 수가 적어진다.
<br>
```cpp
#include <math.h>
#include <string> …
```
> 25-yuyu0830

- seongwon030/수학/두 원.py
[두 원](https://www.acmicpc.net/problem/7869)
4시간
두 원이 겹치는 영역의 넓이를 구하는 문제입니다
**변수는 이렇게 가정합니다**
```
x1,y1 : 좌표
r1 : 반지름
d : 두 원의 중심 간 거리
```
1. 겹치는 영역의 넓이가 0일 때
- 서로 포함관계가 아니며 외접일 때
- 이때는 두 원의 <code>반지름 합</code>이 <code>중심 간 거리</code>보다 작거나 같아야 합니다.
```python 
if r1+r2 <= d:
print(format(0,".3f"))
```
2. 큰 원이 작은 원을 포함할 때
- 작은 원의 크기가 겹치는 영역의 넓이가 됩니다
- 두 원의 <code>반지름 차</code>가 <code>중심 간 거리</code>보다 크거나 같아야 작은원이 큰원을 침범하지 않습니다.
```python
elif abs(r1-r2) >= d :
result = math.pi*min(r1,r2)**2
print( format(result,".3f"))
```
3. 두 원이 서로 다른 두 점에 만날 때
이런 삼각형이 주어졌을 때, 각BAC를 구하려면, 각을 마주보고 있는 직선인 <code>a의 제곱</code>은 각을 끼고 있는 두 직선 <code>b,c의 각각의 제곱에서 b,c의 내적값의 2배 해준 값을 빼준</code> 것과 같다.
여기서 각을 구하기 위해선 역삼각함수를 이용해 구한다.
**겹치는 영역 구하기**
코사인 제2법칙으로 세타1과 세타2를 구해줍니다.
<code>총 넓이 = 큰 원의 부채꼴에서 삼각형을 뺀 것 + 작은 원의 부채꼴에서 …
> 25-seongwon030

- InSange/BFS/310_Minimum Height Trees.cpp
- InSange/README.md
- InSange/문자열/2678_Number of Senior Citizens.cpp
- InSange/수학/840_Magic Squares In Grid.cpp
[number-of-senior-citizens](https://leetcode.com/problems/number-of-senior-citizens/)
30분
입력 값인 `details` 배열에 폰 넘버, 성별, 나이, 좌석 번호가 문자열로 연결된 상태로 주어진다.
`7868190130M7522`에서는 `7868190130`이 폰 번호, `M`이 성별, `75`가 나이, `22`가 좌석 번호가 된다.
주어진 문자열 중에서 나이가 60보다 큰 사람들의 수를 나타내면 됨!
문제 개요에 설명이 되어 있는 것처럼 앞의 10자는 번호, 그 다음 성별, 나이가 주어진다. 고로 문자열의 11번, 12번 인덱스의 값을 참조하여 풀면 된다.
1. 문자열 11번과 12번을 구한다.
2. 문자열을 정수로 변환한다.
3. 60보다 큰 정수 값들을 찾아서 `ans`에 1씩 더해준다.
```c++
public:
int countSeniors(vector<string>& details) {
int ans = 0;
for(string detail : details)
{
string age = "";
age += detail[11];
age += detail[12];
if(stoi(age) > 60) ans++; 
}
return ans;
}
};
```
이러한 방식으로 풀었을 때
최적화가 고려되지 않아서
상위 6%대에 머물게 된다.
아마 stoi 형식이 문자열 전체를 순회하면서 각 문자를 숫자로 변환하고, 자릿수에 맞게 계산하기에 시간 복잡도는 문자열의 길이에 비례하여 O(n)이기에 그런 것 같다.
그 …
> 27-InSange

- InSange/BFS/310_Minimum Height Trees.cpp
- InSange/README.md
- InSange/문자열/2678_Number of Senior Citizens.cpp
- InSange/백트래킹/6987.cpp
- InSange/수학/840_Magic Squares In Grid.cpp
[월드컵](https://www.acmicpc.net/problem/6987)
하루
이미지에 나와 있듯이 각 국 끼리 서로 경기를 한 번 씩 진행하였을 때 나올 수 있는 결과이면은 1을 출력, 결과가 나올 수 없는 경우의 수라면 0을 출력하라
되게 간단하게 풀 수 있을 줄 알았다.
하나의 나라를 지정했을 때 나 올 수 있는 경기의 수는 5번 이므로 승리, 무승부, 패배를 다 더했을 때 5가 나와야 한다!
그리고 전체의 나라를 비교했을 때 승의 개수는 패배의 개수와 같아야 하며 총 30번(6개국 * 5번 경기) 의 경기 중에 승, 패를 제외하면 무승부 값이 나오며 해당 무승부의 값이 0이 나오면 통과! (`draw`가 0보다 작거나 같을 때 입력 받은 `draw`값을 더해주고 `draw`가 0보다 클 때는 빼주는 방식)
정리를 하면
1. 승, 무승부, 패배를 더 했을 때 5가 나와야 한다.
2. 승과 패배의 개수는 같아야 한다. 즉 승과 패배를 뺐을 때 0이 나와야 함
3. 무승부 역시 0이 나와야 한다. -> 0보다 작거나 같을 때는 더해주고 0보다 클 때는 빼주는 형식
4. 총 경기의 수가 30이어야 한다.
```c++
#include <vector>
vector<vector<int>> play;
int win, draw, lose, a, b, c, t, playtime;
bool draw_flag, flag;
void Solve()
{
play.assign(6, vector<int>(3, 0));
t = 4;
while (t--) …
```
> 28-InSange

- seongwon030/다익스트라/최소비용 구하기2.py
[최소비용구하기2](https://www.acmicpc.net/problem/11779)
2시간
정점과 간선 사이의 비용이 주어지고 출발 지점에서 도착 지점에 주어질 때, 출발 지점에서 도착 지점까지의 최소 비용, 최소 비용을 갖는 경로에 포함되어있는 도시의 개수를 출력한다. 출발 도시와 도착 도시도 포함한다.
해당 문제는 다익스트라 알고리즘으로 최소비용을 갱신하면서 최소비용을 구해야 합니다.
출력과정에서 이전 노드를 기록하고 출력하는데 애를 좀 먹었습니다.
```python
def di(start):
q = []
heapq.heappush(q, [0,start]) # 시작노드는 거리가 0 / 시작노드 번호
distance[start] = 0 # 첫 노드 비용을 0으로 설정 
while q:
dist, node = heapq.heappop(q)
if distance[node] < dist:  # 현재 꺼낸 거리가 기존 최단거리보다 크면 스킵
continue
for n,w in graph[node]: # 현재 노드의 인접 노드 탐색
cost = dist + w # 가중치 더해서 새로운 거리를 계산
if distance[n] > cost: # 기존 거리보다 짧으면 갱신
distance[n]= cost  
prev_node[n] = node  # 이전 노드를 기록
heapq.heappush(q,[cost,n]) # 갱신된 인접 노드를 큐에 추가 
```
- 이전노드 기록은 <code>prev_node</code> 리스트에 저장해놓습니다.
- 다음 노드를 갱신하는 경우에만 기록합니다.
```python
di(v1) …
```
> 27-seongwon030

- yuyu0830/README.md
- yuyu0830/탐색/2473.cpp
[세 용액](https://www.acmicpc.net/problem/2473)
3일...? 여튼 꽤 긴 시간
---
두 용액과는 다르다! 3가지 용액을 섞어서 0에 가깝게 만들어야하기 때문에 조금 다른 풀이가 필요할 것이라고 생각했다...
5000 개의 수 중에서 3개를 고르는 경우의 수는 노올랍게도 20,820,835,000 개의 경우의 수가 있다...! 완전 탐색은 절대 불가능 하다고 볼 수 있다..
그럼 최대한 줄일 수 있는 방법이 뭐가 있을까.
5000 개의 수 중에서 2개를 고르는 경우의 수는 12,497,500 개로, 아직 크지만 그래도 경우의 수를 상당히 줄일 수 있다. 그리고 2개의 숫자 합이 정해졌다면, 이분 탐색을 통해 3가지 숫자의 합을 0에 최대로 가깝게 만드는 숫자를 비교적 빠르게 찾을 수 있다. 즉 `n^2 log n` 의 시간 복잡도로 찾을 수 있다.
하지만 이 풀이에는 2가지 문제가 있다.
첫 번째는 우선 줄인 시간복잡도도 충분히 큰 수라는 것이고, 두 번째는 이분 탐색을 할 때 현재 고른 수를 제외하고 나머지 중에서만 찾아야하기에 해당 기능을 구현하기가 조금 빡빡하다는 것이다. 그래서 오래오래 고민하다 결국 [블로그 풀이](https://velog.io/@rhkswls98/%EB%B0%B1%EC%A4%80-2473-C-%EC%84%B8-%EC%9A%A9%EC%95%A1) 를 참고했다..
---
여기서 좀 더 주로 다뤘어야하는 알고리즘은 투 포인터 였다! 굳이 2개를 미리 정해두고 나머지 하나를 찾는게 아닌 **한 개의 수만 정해둔 뒤 나머지 숫자중 가장 0에 가까울 조합을 투 …
> 27-yuyu0830

- InSange/README.md
- InSange/문자열/564_Find the Closest Palindrome.cpp
- InSange/백트래킹/6987.cpp
- InSange/연결 리스트/3217_Delete Nodes From Linked List Present in Array.cpp
[Delete Nodes From Linked List Present in Array](https://leetcode.com/problems/delete-nodes-from-linked-list-present-in-array/)
30분
정수형 연결리스트 `head`와 정수 배열 `nums`가 매개 변수로 주어졌을 때 `nums`안에 속한 노드들을 뺀 연결리스트를 출력
문제를 잘 못 이해하였다. 그러나 큰 틀은 달라진게 없어서 금방 고칠 수 있었음.
처음에 `nums`에 속하지 않는 값을 지닌 노드들을 제거하는 줄 알았다.
그러나 문제를 다시 읽었을 때 반대였다는 것을 깨달음.
1. `nums`에 속하는 값들을 맵에 추가하여 분류해준다. (`um`에 존재하는 값 = 빼야하는 값)
2. 현재 노드가 `um`에 속한 값일 경우 `removeList`의 next 노드 값을 현재 `head`값으로 세팅해주고 업데이트 해준다.
3. 만약 `removeList`가 `nullptr`일 경우 현재 `head`를 세팅.
4. 그렇지 않을 경우. 다음 노드를 탐색.
```c++
public:
ListNode* modifiedList(vector<int>& nums, ListNode* head) {
ListNode* removeList = nullptr;
ListNode* removeHead = nullptr;
unordered_map<int, bool> um;
for(int& val : nums) um[val] = true;
while(head != nullptr)
{
cout << …
```
> 30-InSange

- InSange/DFS/2097 Valid Arrangement of Pairs.cpp
- InSange/README.md
- InSange/문자열/564_Find the Closest Palindrome.cpp
- InSange/백트래킹/6987.cpp
- InSange/연결 리스트/3217_Delete Nodes From Linked List Present in Array.cpp
[Valid Arrangement of Pairs](https://leetcode.com/problems/valid-arrangement-of-pairs/)
3시간
그래프 문제로 간선에 대한 정보들을 2차원 배열 형태로 주어진다.
Input: pairs = [[5,1],[4,5],[11,9],[9,4]]
첫 번째 노드는 출발지고 두 번째 요소로 주어지는 노드는 도착지이다.
5 -> 1
4 -> 5
11 -> 9
9 -> 4
어떤 노드에서 출발을 하였을 때 해당 간선들을 모두 이용하여 유효한 그래프를 만들어야 한다.
즉, 주어진 pairs의 간선들을 모두 사용해서 각 노드들을 통과하는 연속된 배열을 표현해야함.
중요한 점은 주어지는 간선은 무조건 유효하다는 점.
이렇게 중간 노드에서 다른 노드로 간 후 다른 간선들을 이용할 수 없는 경우가 없다.
위의 예제로 이런 식으로 모든 간선들을 활용해서 유효한 그래프를 만들어야 한다.
무조건 유효하다는 점에서 모든 간선들을 다 이용할 때 두 가지의 경우를 생각할 수 있다.
1. 위의 그림 처럼 모든 노드들이 동일하게 하나의 간선으로 이어져 있거나 N개의 간선으로 이어져 있을 경우.
2. 어떤 특정한 노드에서 진출 차수(OutDegree)가 진입 차수(InDegree)보다 1 많을 경우. 이 경우 해당 노드에서 출발을 해주어야 돌고 돌아 N번의 진입 차수 만큼 돌았을 때 나머지 한 경로를 따라 갈 수 있기 때문이다.
Constraints:
1 <= pairs.length <= 10^5
pairs[i].length == 2
0 <= starti, endi <= 10^9 …
> 31-InSange
